import { useState } from 'react'
import { Sparkles, RefreshCw, AlertTriangle, Activity, BarChart2, Zap } from 'lucide-react'
import useLogStore from '../store/useLogStore'
import { fetchAiSummary } from '../services/api'

export default function AiSummary() {
  const { stats, anomalies } = useLogStore()
  const [summary,   setSummary]   = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [generated, setGenerated] = useState(false)
  const [error,     setError]     = useState('')

  const handleGenerate = async () => {
    setIsLoading(true)
    setError('')
    try {
      const { data } = await fetchAiSummary()
      setSummary(data.summary || 'No summary returned.')
      setGenerated(true)
    } catch (err) {
      setError('Failed to generate summary. Make sure Ollama is running and Mistral is pulled.')
    } finally {
      setIsLoading(false)
    }
  }

  const topTypes = Object.entries(
    anomalies.reduce((acc, a) => {
      acc[a.anomalyType] = (acc[a.anomalyType] || 0) + 1
      return acc
    }, {})
  ).sort((a, b) => b[1] - a[1]).slice(0, 5)

  const anomalyRate  = parseFloat(stats.anomalyRate) || 0
  const healthScore  = Math.max(0, Math.round(100 - anomalyRate * 2))
  const healthColor  = healthScore >= 80 ? '#4ade80' : healthScore >= 50 ? '#ffd700' : '#ff3b3b'
  const healthLabel  = healthScore >= 80 ? 'Healthy' : healthScore >= 50 ? 'Degraded' : 'Critical'

  return (
    <div style={{
      flex: 1, overflowY: 'auto',
      padding: '32px 40px',
      background: '#0a0c10',
    }}>
      <div style={{ maxWidth: '760px', width: '100%' }}>

        {/* ── Page Title ── */}
        <div style={{ marginBottom: '32px' }}>
          <h1 style={{
            fontSize: '18px', fontWeight: 700,
            color: '#e2e8f0', display: 'flex',
            alignItems: 'center', gap: '10px',
            marginBottom: '6px',
          }}>
            <Sparkles size={20} color="#00d4ff" />
            AI Health Summary
          </h1>
          <p style={{
            fontSize: '11px', color: '#4a5568',
            fontFamily: 'monospace', letterSpacing: '0.3px',
          }}>
            Generated by Mistral via Ollama — requires backend + Ollama running
          </p>
        </div>

        {/* ── Stats Cards ── */}
        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '16px', marginBottom: '28px',
        }}>

          {/* Health Score */}
          <div style={{
            background: '#0f1218', border: '1px solid #1e2530',
            borderRadius: '14px', padding: '22px',
            borderTop: `3px solid ${healthColor}`,
          }}>
            <div style={{
              display: 'flex', alignItems: 'center', gap: '8px',
              fontSize: '10px', fontFamily: 'monospace',
              color: '#4a5568', letterSpacing: '1.5px',
              textTransform: 'uppercase', marginBottom: '12px',
            }}>
              <Activity size={12} color="#4a5568" />
              Health Score
            </div>
            <div style={{
              fontSize: '42px', fontWeight: 800,
              color: healthColor, fontFamily: 'monospace',
              lineHeight: 1, marginBottom: '6px',
            }}>
              {healthScore}
            </div>
            <div style={{
              fontSize: '12px', fontWeight: 600,
              color: healthColor, fontFamily: 'monospace',
            }}>
              {healthLabel}
            </div>
          </div>

          {/* Analyzed */}
          <div style={{
            background: '#0f1218', border: '1px solid #1e2530',
            borderRadius: '14px', padding: '22px',
            borderTop: '3px solid #00d4ff',
          }}>
            <div style={{
              display: 'flex', alignItems: 'center', gap: '8px',
              fontSize: '10px', fontFamily: 'monospace',
              color: '#4a5568', letterSpacing: '1.5px',
              textTransform: 'uppercase', marginBottom: '12px',
            }}>
              <BarChart2 size={12} color="#4a5568" />
              Analyzed
            </div>
            <div style={{
              fontSize: '42px', fontWeight: 800,
              color: '#00d4ff', fontFamily: 'monospace',
              lineHeight: 1, marginBottom: '6px',
            }}>
              {stats.totalLogs}
            </div>
            <div style={{ fontSize: '11px', color: '#4a5568' }}>
              total log lines
            </div>
          </div>

          {/* Anomaly Rate */}
          <div style={{
            background: '#0f1218', border: '1px solid #1e2530',
            borderRadius: '14px', padding: '22px',
            borderTop: '3px solid #ff8c00',
          }}>
            <div style={{
              display: 'flex', alignItems: 'center', gap: '8px',
              fontSize: '10px', fontFamily: 'monospace',
              color: '#4a5568', letterSpacing: '1.5px',
              textTransform: 'uppercase', marginBottom: '12px',
            }}>
              <Zap size={12} color="#4a5568" />
              Anomaly Rate
            </div>
            <div style={{
              fontSize: '42px', fontWeight: 800,
              color: '#ff8c00', fontFamily: 'monospace',
              lineHeight: 1, marginBottom: '6px',
            }}>
              {stats.anomalyRate}
            </div>
            <div style={{ fontSize: '11px', color: '#4a5568' }}>
              {stats.totalAnomalies} anomalies found
            </div>
          </div>
        </div>

        {/* ── Top Anomaly Types ── */}
        {topTypes.length > 0 && (
          <div style={{
            background: '#0f1218', border: '1px solid #1e2530',
            borderRadius: '14px', padding: '22px',
            marginBottom: '28px',
          }}>
            <div style={{
              fontSize: '10px', fontFamily: 'monospace',
              color: '#4a5568', letterSpacing: '1.5px',
              textTransform: 'uppercase', marginBottom: '18px',
              display: 'flex', alignItems: 'center', gap: '8px',
            }}>
              <BarChart2 size={12} color="#4a5568" />
              Top Anomaly Types
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              {topTypes.map(([type, count]) => {
                const pct = Math.round((count / anomalies.length) * 100)
                return (
                  <div key={type}>
                    <div style={{
                      display: 'flex', justifyContent: 'space-between',
                      marginBottom: '6px',
                    }}>
                      <span style={{
                        fontSize: '12px', fontWeight: 600,
                        color: '#e2e8f0', fontFamily: 'monospace',
                      }}>
                        {type}
                      </span>
                      <span style={{
                        fontSize: '11px', color: '#4a5568',
                        fontFamily: 'monospace',
                      }}>
                        {count} ({pct}%)
                      </span>
                    </div>
                    {/* Progress Bar */}
                    <div style={{
                      height: '6px', borderRadius: '3px',
                      background: '#141820', overflow: 'hidden',
                    }}>
                      <div style={{
                        height: '100%', borderRadius: '3px',
                        width: `${pct}%`,
                        background: 'linear-gradient(90deg, #00d4ff, #0066ff)',
                        transition: 'width 0.5s ease',
                      }} />
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* ── AI Summary Box ── */}
        <div style={{
          background: 'linear-gradient(135deg, rgba(0,212,255,0.05), rgba(0,102,255,0.05))',
          border: '1px solid rgba(0,212,255,0.2)',
          borderRadius: '14px', padding: '24px',
          marginBottom: '20px',
        }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: '8px',
            fontSize: '10px', fontFamily: 'monospace',
            color: '#00d4ff', letterSpacing: '1.5px',
            textTransform: 'uppercase', marginBottom: '16px',
          }}>
            <Sparkles size={13} color="#00d4ff" />
            Mistral AI Analysis
          </div>

          {/* Loading */}
          {isLoading && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', padding: '8px 0' }}>
              <div className="loading-bar" />
              <div style={{ fontSize: '12px', color: '#4a5568', fontFamily: 'monospace' }}>
                Generating summary with Mistral...
              </div>
            </div>
          )}

          {/* Error */}
          {error && !isLoading && (
            <div style={{
              display: 'flex', alignItems: 'flex-start', gap: '10px',
              padding: '14px 16px', borderRadius: '10px',
              background: 'rgba(255,59,59,0.08)',
              border: '1px solid rgba(255,59,59,0.25)',
              color: '#ff3b3b', fontSize: '13px',
            }}>
              <AlertTriangle size={16} style={{ flexShrink: 0, marginTop: '1px' }} />
              {error}
            </div>
          )}

          {/* Placeholder */}
          {!generated && !isLoading && !error && (
            <div style={{
              textAlign: 'center', padding: '24px 0',
              fontSize: '13px', color: '#4a5568',
            }}>
              Click the button below to generate your AI health summary
            </div>
          )}

          {/* Summary Text */}
          {generated && !isLoading && (
            <div style={{
              fontSize: '14px', lineHeight: '1.8',
              color: '#8892a4',
            }}>
              {summary}
            </div>
          )}
        </div>

        {/* ── Generate Button ── */}
        <button
          onClick={handleGenerate}
          disabled={isLoading}
          style={{
            display: 'inline-flex', alignItems: 'center', gap: '10px',
            padding: '12px 28px', borderRadius: '12px',
            fontSize: '14px', fontWeight: 600,
            border: 'none', cursor: isLoading ? 'not-allowed' : 'pointer',
            background: isLoading
              ? 'rgba(0,212,255,0.3)'
              : 'linear-gradient(135deg, #00d4ff, #0066ff)',
            color: '#000',
            transition: 'all 0.15s',
          }}
        >
          <RefreshCw size={16} />
          {isLoading ? 'Generating...' : generated ? 'Regenerate Summary' : 'Generate AI Summary'}
        </button>

        <p style={{
          fontSize: '11px', color: '#4a5568',
          fontFamily: 'monospace', marginTop: '14px',
        }}>
          Requires Ollama running at localhost:11434 with mistral model pulled
        </p>

      </div>
    </div>
  )
}